apiVersion: v1
kind: ConfigMap
metadata:
  name: environment
data:
  # each key is a deployment name
  # value is a JSON array of {name, value} object
  nginx: |
    [
        {
            "name": "ENV_VAR_3",
            "value": "env_var_3_value"
        },
        {
            "name": "ENV_VAR_2",
            "value": "env_var_2_value"
        }
    ]
  demo: |
    [
        {
            "name": "ENV_VAR_3",
            "value": "env_var_3_value"
        },
        {
            "name": "ENV_VAR_2",
            "value": "env_var_2_value"
        }
    ]