apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-env-manager
  name: k8s-env-manager
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: k8s-env-manager
